/*creating Listing  
---Informed consent
---16.2_1_2*/

/*calling the ADam library into work */
libname ADaM "D:\HARSHINI\CDISC\ADaM dataset-20240301T022624Z-001\ADaM dataset";

/*filtering the variables*/
Data ADSL1;
SET ADaM.ADSL;
KEEP USUBJID RFICDTC;
RUN;

%INCLUDE "D:\HARSHINI\CDISC\Macros\RTF.SAS";

Title1 J=L "Genesis, Inc.";
Title2 J=L "Protocol#: MMSC 2023-01";
title3 J=C "16.2.1.2 Informed Consent";

FOOTNOTE J=L "D:\HARSHINI\CDISC\My practice\PROJECT\Programs\16_2_1_2.sas";

ODS ESCAPECHAR='^';
OPTIONS ORIENTATION= LANDSCAPE;
ODS RTF FILE="D:\HARSHINI\CDISC\My practice\PROJECT\output\16_2_1_2.RTF" STYLE=styles.test;

PROC REPORT DATA=ADSL1 NOWD SPLIT="|" STYLE={OUTPUTWIDTH=100%};
COLUMN USUBJID RFICDTC;

DEFINE USUBJID/"Subject Number"
STYLE (HEADER)={JUST=L CELLWIDTH=50%}
STYLE (COLUMN)={JUST=L CELLWIDTH=50%};

DEFINE RFICDTC/"Date of Informed Consent"
STYLE (HEADER)={JUST=L CELLWIDTH=49%}
STYLE (COLUMN)={JUST=L CELLWIDTH=49%};

COMPUTE BEFORE _PAGE_;
LINE @1 "^{STYLE[OUTPUTWIDTH=100% BORDERTOPWIDTH=0.5PT]}";
ENDCOMP;

COMPUTE AFTER _PAGE_;
LINE @1 "^{STYLE[OUTPUTWIDTH=100% BORDERTOPWIDTH=0.5PT]}";
ENDCOMP;

RUN;


ODS _ALL_ CLOSE;

